#!/bin/sh
# $Id: addcrc-cksfv,v 1.3 2006/12/12 19:52:47 dm Exp $
for name in "$@"
do
	if test ! -f "${name}"
	then
		continue
	fi
	sum1=`cksfv "${name}" |
	tail -n 1 |
	awk '{print $NF}'`
	sum2=`echo "${sum1}" | tr '[A-Z]' '[a-z]'`
	case "${name}" in
	*${sum1}*|*${sum2}*)
		echo "crc ok: ${name}"
		continue
		;;
	*)
		dir="${name%/*}"
		if test "${dir}" = "${name}"
		then
			dir="."
		fi
		file="${name##*/}"
		neu="${file%.*}[${sum1}].${file##*.}"
		neu=`echo ${neu} | sed -e "s= =_=g"`
		neu="${dir}/${neu}"
		echo \
		mv -i "${name}" "${neu}"
		mv -i "${name}" "${neu}"
		;;
	esac
done
