#!/bin/sh
for name in "$@"
do
	if test ! -f "${name}"
	then
		continue
	fi
	sum1=`cksfv "${name}" |
	tail -n 1 |
	awk '{print $NF}'`
	sum2=`echo "${sum1}" | tr '[A-Z]' '[a-z]'`
	case "${name}" in
	*${sum1}*|*${sum2}*)
		echo "crc ok: ${name}"
		continue
		;;
	*)
		neu="${name%.*}[${sum1}].${name##*.}"
		neu=`echo ${neu} | sed -e "s= =_=g"`
		echo \
		mv -i "${name}" "${neu}"
		mv -i "${name}" "${neu}"
		;;
	esac
done
