#!/bin/sh
# $Id: addcrc,v 1.4 2006/02/10 18:30:20 dm Exp $
for name in "$@"
do
	if test -f "${name}"
	then
		continue
	fi
	sum1=`cksum -o 3 "${name}" |
	awk '{
		CRC = $1
		if ( CRC > 2^31 )
			CRC -= 2^32
		$1 = sprintf( "%08X", CRC )
		$2 = ""
		print $1
	}'`
	sum2=`echo "${sum1}" | tr '[A-Z]' '[a-z]'`
	case "${name}" in
	*${sum1}*|*${sum2}*)
		echo "crc ok: ${name}"
		continue
		;;
	*)
		dir="${name%/*}"
		file="${name##*/}"
		neu="${file%.*}[${sum1}].${file##*.}"
		neu=`echo ${neu} | sed -e "s= =_=g"`
		neu="${dir}/${neu}"
		echo \
		mv -i "${name}" "${neu}"
		mv -i "${name}" "${neu}"
		;;
	esac
done
