#!/bin/sh
for name in "$@"
do
	sum1=`cksum -o 3 "${name}" |
	awk '{
		CRC = $1
		if ( CRC > 2^31 )
			CRC -= 2^32
		$1 = sprintf( "%08X", CRC )
		$2 = ""
		print $1
	}'`
	sum2=`echo "${sum1}" | tr '[A-Z]' '[a-z]'`
	case "${name}" in
	*${sum1}*|*${sum2}*)
		echo "crc ok: ${name}"
		continue
		;;
	*)
		neu="${name%.*}[${sum1}].${name##*.}"
		neu=`echo ${neu} | sed -e "s= =_=g"`
		echo \
		mv -i "${name}" "${neu}"
		mv -i "${name}" "${neu}"
		;;
	esac
done
