#!/usr/bin/awk -f
BEGIN {
}
function ausgabe() {
	PACK ++

	if ( SEEN[ XF ] == "" ) {
		SEEN[ XF ] = PACK
		return
	}

	printf( "%3s %s\n", "#" SEEN[ XF ], XD )
	printf( "%3s %s\n", "#" PACK, XD )
	print ""
}
END {
	ausgabe()
}
/Do Not Edit This File/ {
#	Do Not Edit This File: 50.08 50.43 15173264677 1638743
	if ( LAST_KEY != "" ) {
		ausgabe()
		XF = ""
		print ""
	}
	PACK = 0
}
/^$/ {
	if ( XF == "" )
		next

	ausgabe()
}
/^xx_file/ {
	XF = substr( $0, 9 )
	next
}
/^xx_desc/ {
	XD = substr( $0, 9 )
	next
}
/^xx_trno/ {
	XT = substr( $0, 9 )
	next
}
#
