#!/usr/bin/awk -f
BEGIN {
	DATA = ""
	if ( GREP == "" ) {
		print "add to cmmandline: -v GREP=pattern xddc.state"
		exit
	}
}
function ausgabe() {
	if ( DATA != "" ) {
		if ( DATA ~ GREP )
			print DATA
		DATA = ""
	}
}
END {
	ausgabe()
}
/Do Not Edit This File/ {
	ausgabe()
}
/^$/ {
	ausgabe()
}
/^xx_/ {
	DATA = DATA "\n" $0
	next
}
# eof
